### ISSUE TITLE
Herstellen des originalen Setups

### ISSUE THREAD

**Issue by geccy25** [twenty-eight-days/TwentyEightDaysNative#13]
Wir haben uns dafür entschieden, das orignale Setup wieder herzustellen.

**Comment by geccy25** [comment]
Setup wurde wieder hergestellt mit IntelliJ compare.
Funktioniert bei:
- [x] Herr Gamez
- [x] Frau Hofmann

**Comment by geccy25** [comment]
Ich bekomme weiterhin prettier error Meldungen und kann deshalb nicht Commiten.
Verify gibt Konflickt an.

**Comment by geccy25** [comment]
Git hatte als Branch head main, wurde abgeändert zu local main mit der Verbindung zu origin main.
git reset  --hard origin/main
Konflikt wurde somit behoben und auch die prettier Fehlermeldungen.
Setup ist nun auch bei mir funktionsfähig

**Comment by PiecePaperCode** [comment]
namens Collision mit app.json und package.json Grossbuchstaben haben nicht gematcht
```json
{
  "name": "twentyeightdaysnative",
  "displayName": "TwentyEightDaysNative"
}
```

**Comment by geccy25** [comment]
Da bei mir immer wieder der git precommit von Husky mit ESLint failed, musste immer wieder folgende commands ausgeführt werden:

```sh
git revert --hard origin/main //reset von HEAD zurück auf MAIN
yarn lint --fix //fixen des commit Issues in IntelliJ
yarn install
git commit --no-verify
```
