### ISSUE TITLE
Tests schreiben für calculate.ts

### ISSUE THREAD

**Issue by geccy25** [twenty-eight-days/TwentyEightDaysNative#20]

**Comment by PiecePaperCode** [comment]
https://github.com/twenty-eight-days/TwentyEightDaysNative/commit/5b9a5357ece601c3af04c8208ab5f563b45de43f

**Comment by PiecePaperCode** [comment]
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |   81.66 |    71.42 |   60.86 |   83.92 |                   
 src                 |     100 |      100 |     100 |     100 |                   
  App.ts             |     100 |      100 |     100 |     100 |                   
 src/controller      |     100 |      100 |     100 |     100 |                   
  calculate.ts       |     100 |      100 |     100 |     100 |                   
 src/model           |   78.57 |     90.9 |   41.66 |   80.48 |                   
  exampleSlice.ts    |      50 |      100 |       0 |      50 | 10-13             
  index.ts           |      75 |      100 |   33.33 |   85.71 | 23                
  storage.ts         |   83.33 |     90.9 |   57.14 |   83.33 | 28,36-39,65       
 src/view/components |   73.68 |       50 |   63.63 |   77.77 |                   
  buttons.tsx        |     100 |      100 |     100 |     100 |                   
  datePicker.tsx     |   57.14 |       50 |   33.33 |   57.14 | 14-23             
  periodTable.tsx    |   66.66 |      100 |      60 |      80 | 22                
 src/view/containers |   74.19 |    33.33 |   61.11 |   77.77 |                   
  DataScreen.tsx     |     100 |      100 |     100 |     100 |                   
  Footer.tsx         |      75 |      100 |   66.66 |      75 | 20                
  Header.tsx         |     100 |      100 |     100 |     100 |                   
  MainScreen.tsx     |   46.15 |    33.33 |   33.33 |      50 | 31-43             
  Screen.tsx         |     100 |      100 |     100 |     100 |                   
 src/view/ressources |     100 |      100 |     100 |     100 |                   
  table.png          |     100 |      100 |     100 |     100 |                   
  today.png          |     100 |      100 |     100 |     100 |                   
  white_today.png    |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       15 passed, 15 total
Snapshots:   0 total
Time:        2.135 s
Ran all test suites.
