### ISSUE TITLE
Bar chart

### ISSUE THREAD

**Issue by geccy25** [twenty-eight-days/TwentyEightDaysNative#22]
Bar Chart für Cycle Duration einbinden mit https://d3js.org/

**Comment by PiecePaperCode** [comment]
Jest would not test the Barchart Library.
This problem is mitigated by using following jest configuration inside the package.json
```json
"jest": {
    "preset": "react-native",
    "transform": {},
    "transformIgnorePatterns": [
      "/node_modules/(?!(@react-native|react-native|react-native-chart-kit|@react-native-community/datetimepicker)/).*/"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
```

**Comment by PiecePaperCode** [comment]
![image](https://user-images.githubusercontent.com/40020346/147295704-5d3e1e1e-73de-4503-a9ed-6158fe466007.png)
Implemented with react-native-chart-kit
