### ISSUE TITLE
Daten auslesen und als Liste anzeigen

### ISSUE THREAD

**Issue by geccy25** [twenty-eight-days/TwentyEightDaysNative#7]

**Comment by geccy25** [comment]
# Aufgaben

- [x] Entfehrenen des Standart Hallo React Interface

- [x] Erstes einfaches Start Interface der App

**Comment by PiecePaperCode** [comment]
https://github.com/twenty-eight-days/TwentyEightDaysNative/commit/7c1ce4365e45a5722edb78ecf4a8713d3df274e0
<img src="https://user-images.githubusercontent.com/40020346/145070323-f609b3ef-aae2-4dc9-9914-8c940a138e27.png" width=400/>
