### ISSUE TITLE
Löschen einzelner Items unterstützen

### ISSUE THREAD

**Issue by geccy25** [twenty-eight-days/TwentyEightDaysNative#8]
- [X] Delete Items (periods) of the List
- [x] Swipe to delete or double click by asking the user if he want to delete

**Comment by PiecePaperCode** [comment]
# Documentation:
Löschen eines Elementes soll durch eine Swipe Bewegung löschbar sein.
[https://codedaily.io/tutorials/React-Native-Animated-ScrollView-Row-Swipe-Actions](https://codedaily.io/tutorials/React-Native-Animated-ScrollView-Row-Swipe-Actions)
![z1tko0s-827ba4287c](https://user-images.githubusercontent.com/40020346/145048503-904748fe-bbbe-4333-8ddf-304e72c3e28e.gif)

**Comment by PiecePaperCode** [comment]
# Period List
![image](https://user-images.githubusercontent.com/40020346/145070878-7acaa67e-5bb1-4eb6-b5dd-1e967a963424.png)
## Click on one Item and it will be deleted
![image](https://user-images.githubusercontent.com/40020346/145070937-74ddf445-686b-4ed5-a846-fb97aafd4595.png)

**Comment by geccy25** [comment]
Musste heute IntelliJ und diverse Features upgraden, worauf dann auch meine Plugin Fehlermeldung verschwand

**Comment by geccy25** [comment]
Musste nach dem Update von IntelliJ den root folder under Projekt Structure wiederherstellen
![image](https://user-images.githubusercontent.com/95216778/145211697-b1a1ebcd-c420-40ad-8fbb-a43b832efa20.png)
